apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-07-08T06:03:02Z"
  labels:
    app: n1
  name: n1
  namespace: default
  resourceVersion: "396485"
  uid: a305580c-4230-494f-b877-6f4d78433c79
spec:
  clusterIP: 10.233.27.139
  clusterIPs:
  - 10.233.27.139
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32402
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: n1
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
